<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectTypes [
	<!ELEMENT projectTypes (projectType+)>
	<!ELEMENT projectType (nature*, classpath?, files)>
	<!ATTLIST projectType
	name CDATA #REQUIRED
		id ID #REQUIRED
>
	<!ELEMENT nature EMPTY>
	<!ATTLIST nature
	id CDATA #REQUIRED
>
	<!ELEMENT classpath (classpathentry+)>
	<!ATTLIST classpath
	variables CDATA #REQUIRED
>
	<!ELEMENT classpathentry EMPTY>
	<!ATTLIST classpathentry
	kind (lib | output | src | var) #REQUIRED
		path CDATA #REQUIRED
		rootpath CDATA #IMPLIED
		sourcepath CDATA #IMPLIED
>
	<!ELEMENT files (file+)>
	<!ELEMENT file EMPTY>
	<!ATTLIST file
	templateId (application | session | directAction | project | properties | makefile | makefile.preamble | makefile.postamble | applicationproject | frameworkproject | subproject | antwoapplication | antwoframework | woapplication.makefile.preamble | woapplication.makefile.postamble | woapplication.makefile | woapplication.custominfo.plist | woapplication.icon | woframework.makefile.preamble | woframework.makefile.postamble | woframework.makefile | woframework.custominfo.plist ) #REQUIRED
		name CDATA #REQUIRED 
>
]>
<projectTypes>
	<projectType name="Java WebObjects Application" id="JavaWebObjectsApplication">
		<nature id="org.eclipse.jdt.core.javanature"/>
		<nature id="org.objectstyle.wolips.applicationnature"/>
		<classpath variables="webobjects.system.library.dir">
			<classpathentry kind="src" path="${project.name}.proj"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaWebObjects.framework/Resources/Java/javawebobjects.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaFoundation.framework/Resources/Java/javafoundation.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaXML.framework/Resources/Java/javaxml.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaWOExtensions.framework/Resources/Java/JavaWOExtensions.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaEOAccess.framework/Resources/Java/javaeoaccess.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaEOControl.framework/Resources/Java/javaeocontrol.jar"/>
			<classpathentry kind="var" path="JRE_LIB" rootpath="JRE_SRCROOT" sourcepath="JRE_SRC"/>
		</classpath>
		<files>
			<file templateId="application" name="Application.java"/>
			<file templateId="session" name="Session.java"/>
			<file templateId="directAction" name="DirectAction.java"/>
			<file templateId="properties" name="Properties"/>
			<file templateId="applicationproject" name="PB.project"/>
			<file templateId="antwoapplication" name="build.xml"/>
			<file templateId="woapplication.makefile.preamble" name="Makefile.preamble"/>
			<file templateId="woapplication.makefile" name="Makefile"/>
			<file templateId="woapplication.makefile.postamble" name="Makefile.postamble"/>
			<file templateId="woapplication.custominfo.plist" name="CustomInfo.plist"/>
			<file templateId="woapplication.icon" name="WOAfile.icns"/>
		</files>
	</projectType>
	<projectType name="Java WebObjects Framework" id="JavaWebObjectsFramework">
		<nature id="org.eclipse.jdt.core.javanature"/>
		<nature id="org.objectstyle.wolips.frameworknature"/>
		<classpath variables="webobjects.system.library.dir">
			<classpathentry kind="src" path="${project.name}.proj"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaWebObjects.framework/Resources/Java/javawebobjects.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaFoundation.framework/Resources/Java/javafoundation.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaXML.framework/Resources/Java/javaxml.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaWOExtensions.framework/Resources/Java/JavaWOExtensions.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaEOAccess.framework/Resources/Java/javaeoaccess.jar"/>
			<classpathentry kind="lib" path="${webobjects.system.library.dir}/Frameworks/JavaEOControl.framework/Resources/Java/javaeocontrol.jar"/>
			<classpathentry kind="var" path="JRE_LIB" rootpath="JRE_SRCROOT" sourcepath="JRE_SRC"/>
		</classpath>
		<files>
			<file templateId="frameworkproject" name="PB.project"/>
			<file templateId="antwoframework" name="build.xml"/>
			<file templateId="woframework.makefile.preamble" name="Makefile.preamble"/>
			<file templateId="woframework.makefile" name="Makefile"/>
			<file templateId="woframework.makefile.postamble" name="Makefile.postamble"/>
			<file templateId="woframework.custominfo.plist" name="CustomInfo.plist"/>
		</files>
	</projectType>
	<projectType name="WebObjects Subproject" id="JavaWebObjectsSubproject">
		<files>
			<file templateId="subproject" name="PB.project"/>
		</files>
	</projectType>
</projectTypes>
